# Exercise 03: Minimum Edit Distance

In [2]:
from typing import List, Union, Dict, Set, Tuple
import numpy as np
from numpy.typing import NDArray

### Task 1: Preprocessing
In this task, use functions from ``nltk`` wherever possible.

In [13]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

__a)__ Write a function that removes the punctuation (consider ``string.punctuation``) and all stopwords from a given text.

In [4]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [6]:
import string

punc = string.punctuation
print(punc)
type(punc)

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~


str

In [9]:
from nltk.corpus import stopwords

stop_words = stopwords.words('english')
print(stop_words)

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [36]:
from nltk.corpus.reader.util import StreamBackedCorpusView

def clean(tokens: Union[List[str], StreamBackedCorpusView]) -> List[str]:
    """
    :param tokens: list of tokens that should be cleaned
    :return: list of cleaned tokens
    """
    # your code here
    punc = string.punctuation
    stop_words = stopwords.words('english')
    clean_results = [w for w in tokens if (w not in punc and w.lower() not in stop_words)]
    return clean_results

In [30]:
list1 = [1, 2, 44, 356]
list2 = [1, 2, 4, 56]
list3 = [44, 'all']
a = [i for i in list1 if not (i in list2 or i in list3)]
a

[356]

In [11]:
# test
t1 = "I am happy to have you my dear friend!~"

In [37]:
from nltk.tokenize import word_tokenize
t1_tokens = word_tokenize(t1)
print(t1_tokens)

print(clean(t1_tokens))

['I', 'am', 'happy', 'to', 'have', 'you', 'my', 'dear', 'friend', '!', '~']
['happy', 'dear', 'friend']


__b)__ Get the list of tokens from the book Moby Dick (``melville-moby_dick.txt``) which you can find in the ``gutenberg`` corpus. Return the word counts sorted by frequency (most frequent word first) before and after cleaning the list of tokens with your function from __a)__.

_Hint: Take a look at_ ``defaultdict`` _and_ ``Counter`` _from the Python module_ ``collections``.

In [62]:
nltk.download('gutenberg')
from nltk.corpus import gutenberg
words = gutenberg.words('melville-moby_dick.txt')
type(words)

[nltk_data] Downloading package gutenberg to /root/nltk_data...
[nltk_data]   Package gutenberg is already up-to-date!


nltk.corpus.reader.util.StreamBackedCorpusView

In [58]:
from collections import defaultdict
word_count = defaultdict(int)
for w in words:
  if w not in punc:
    word_count[w] +=1
#print(word_count)
sorted(word_count.items(), key = lambda item: item[1], reverse = True)

[('the', 13721),
 ('of', 6536),
 ('and', 6024),
 ('a', 4569),
 ('to', 4542),
 ('in', 3916),
 ('that', 2982),
 ('his', 2459),
 ('it', 2209),
 ('I', 2124),
 ('s', 1739),
 ('is', 1695),
 ('he', 1661),
 ('with', 1659),
 ('was', 1632),
 ('as', 1620),
 ('all', 1462),
 ('for', 1414),
 ('this', 1280),
 ('at', 1231),
 ('by', 1137),
 ('but', 1113),
 ('not', 1103),
 ('--', 1070),
 ('him', 1058),
 ('from', 1052),
 ('be', 1030),
 ('on', 1005),
 ('so', 918),
 ('whale', 906),
 ('one', 889),
 ('you', 841),
 ('had', 767),
 ('have', 760),
 ('there', 715),
 ('But', 705),
 ('or', 697),
 ('were', 680),
 ('now', 646),
 ('which', 640),
 ('me', 627),
 ('like', 624),
 ('The', 612),
 ('their', 612),
 ('are', 586),
 ('they', 586),
 ('an', 582),
 ('some', 578),
 ('then', 571),
 ('my', 564),
 ('when', 553),
 ('upon', 538),
 ('out', 529),
 ('into', 520),
 ('man', 508),
 ('ship', 507),
 ('up', 505),
 ('more', 501),
 ('Ahab', 501),
 ('."', 489),
 ('no', 484),
 ('them', 471),
 ('ye', 460),
 ('what', 442),
 ('old', 436

In [64]:
cleanword = clean(words)
cleanword_count = defaultdict(int)
for w in cleanword:
  cleanword_count[w] +=1

sorted(cleanword_count.items(), key = lambda item: item[1], reverse = True)


[('--', 1070),
 ('whale', 906),
 ('one', 889),
 ('like', 624),
 ('upon', 538),
 ('man', 508),
 ('ship', 507),
 ('Ahab', 501),
 ('."', 489),
 ('ye', 460),
 ('old', 436),
 ('sea', 433),
 ('would', 421),
 ('head', 335),
 ('though', 335),
 ('boat', 330),
 ('time', 324),
 ('long', 318),
 ('said', 302),
 (',"', 302),
 ('yet', 300),
 ('still', 299),
 ('great', 293),
 ('two', 285),
 ('seemed', 283),
 ('must', 282),
 ('Whale', 282),
 ('last', 277),
 ('way', 269),
 ('Stubb', 255),
 ('see', 253),
 ('?"', 252),
 ('Queequeg', 252),
 ('little', 247),
 ('round', 242),
 ('whales', 237),
 ('say', 237),
 ('three', 237),
 ('men', 236),
 ('thou', 232),
 ('may', 230),
 ('us', 228),
 ('every', 222),
 ('much', 218),
 ('could', 215),
 ('Captain', 215),
 ('first', 210),
 ('side', 208),
 ('hand', 205),
 ('ever', 203),
 ('Starbuck', 196),
 ('never', 195),
 ('good', 192),
 ('white', 191),
 ('deck', 189),
 ('thing', 188),
 ('almost', 186),
 ('water', 185),
 ('might', 183),
 ('go', 182),
 ('even', 181),
 ('made', 1

In [67]:
from collections import Counter
cleanword = clean(words)
cleanword_count1 = Counter(cleanword)
cleanword_count1.most_common()

[('--', 1070),
 ('whale', 906),
 ('one', 889),
 ('like', 624),
 ('upon', 538),
 ('man', 508),
 ('ship', 507),
 ('Ahab', 501),
 ('."', 489),
 ('ye', 460),
 ('old', 436),
 ('sea', 433),
 ('would', 421),
 ('head', 335),
 ('though', 335),
 ('boat', 330),
 ('time', 324),
 ('long', 318),
 ('said', 302),
 (',"', 302),
 ('yet', 300),
 ('still', 299),
 ('great', 293),
 ('two', 285),
 ('seemed', 283),
 ('must', 282),
 ('Whale', 282),
 ('last', 277),
 ('way', 269),
 ('Stubb', 255),
 ('see', 253),
 ('?"', 252),
 ('Queequeg', 252),
 ('little', 247),
 ('round', 242),
 ('whales', 237),
 ('say', 237),
 ('three', 237),
 ('men', 236),
 ('thou', 232),
 ('may', 230),
 ('us', 228),
 ('every', 222),
 ('much', 218),
 ('could', 215),
 ('Captain', 215),
 ('first', 210),
 ('side', 208),
 ('hand', 205),
 ('ever', 203),
 ('Starbuck', 196),
 ('never', 195),
 ('good', 192),
 ('white', 191),
 ('deck', 189),
 ('thing', 188),
 ('almost', 186),
 ('water', 185),
 ('might', 183),
 ('go', 182),
 ('even', 181),
 ('made', 1

### Task 2: Minimum Edit Distance

__a)__ In this task we want to calculate the minimum edit distance between two input strings.

Write a function that implements the minimum edit distance algorithm (dynamic programming) from the lecture. Your function should get two strings as input and should return the minimum edit distance and a 2-dimensional numpy array that represents the corresponding edit distance table ``D``. Assume that insertion and deletion have a cost of 1. The cost of substitution should be specified by the user (default: 2, i.e., Levenshtein distance).

Note, that the entry ``D[i][j]`` in the returned numpy array should correspond to the cell D(i,j) of the edit distance table from the lecture (i.e. the numpy array is a vertically flipped version of the table from the lecture).

__Example:__ _The edit distance table_ ``D`` _for a source string of length 3 and a target string of length 5 should be initialized as follows:_

```
[[0  1  2  3  4  5]
 [1  0  0  0  0  0]
 [2  0  0  0  0  0]
 [3  0  0  0  0  0]]
```

In [95]:
def edit_distance(str1: str, str2: str, cost_of_substitute: int=2) -> (int, NDArray[NDArray[int]]):
    '''
    :param str1: source string
    :param str2: target string
    :cost_of_substitute: cost for substituting mismatching letters
    :returns:
        - minimum edit distance of str1 and str2
        - minimum edit distance table
    '''
    # your code here
    I = len(str1) + 1
    J = len(str2) + 1
    D = np.zeros((I, J), dtype = int)

    D[:,0] = np.arange(I)
    D[0,:] = np.arange(J)

    for i in range(1, I):
      for j in range(1, J):
        sub = D[i-1, j-1]
        if str1[i-1] != str2[j-1]:
          sub += 2
        D[i,j] = min(D[i-1,j]+1, D[i,j-1]+1, sub)

    return D

In [97]:
str1 = 'pandas'
str2 = 'catt'

edit_distance(str1, str2)

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 2, 3, 4],
       [3, 4, 3, 4, 5],
       [4, 5, 4, 5, 6],
       [5, 6, 5, 6, 7],
       [6, 7, 6, 7, 8]])

In [68]:
string1 = 'apple'
len(string1)

5

In [70]:
b = [i for i in range(4)]
b

[0, 1, 2, 3]