# Exercise 03: Minimum Edit Distance

In [1]:
from typing import List, Union, Dict, Set, Tuple
import numpy as np
from numpy.typing import NDArray, ArrayLike

### Task 1: Preprocessing
In this task, use functions from ``nltk`` wherever possible.

In [2]:
import nltk

__a)__ Write a function that removes the punctuation (consider ``string.punctuation``) and all stopwords from a given text.

In [11]:
nltk.download('stopwords')
nltk.download('punkt')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [34]:
import string

# string with all punctuation symbols
puncts = string.punctuation
print(puncts)
t1 = '--'
t1 in puncts

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~


False

In [15]:
from nltk.corpus import stopwords


# list of stopwords
stop_words = stopwords.words('english')
type(stop_words)

list

In [6]:
from nltk.corpus.reader.util import StreamBackedCorpusView

# solution
def clean(tokens: Union[List[str], StreamBackedCorpusView]) -> List[str]:
    """
    :param tokens: list of tokens that should be cleaned
    :return: list of cleaned tokens
    """
    stop_words = stopwords.words('english')
    punct = string.punctuation

    clean_tokens = [t for t in tokens if not (t.lower() in stop_words or t.lower() in punct)]

    return clean_tokens

In [13]:
def clean1(tokens: Union[List[str], StreamBackedCorpusView]) -> List[str]:
    """
    :param tokens: list of tokens that should be cleaned
    :return: list of cleaned tokens
    """

    removals = stopwords.words('english')
    removals.extend(string.punctuation)
    return [i for i in word_tokenize(tokens) if i.lower() not in removals]


In [9]:
# test
t1 = "I am happy to have you my dear friend!~"

In [14]:
from nltk.tokenize import word_tokenize

t1_tokens = word_tokenize(t1)
print(t1_tokens)

print(clean(t1_tokens))
print(clean1(t1))

['I', 'am', 'happy', 'to', 'have', 'you', 'my', 'dear', 'friend', '!', '~']
['happy', 'dear', 'friend']
['happy', 'dear', 'friend']


__b)__ Get the list of tokens from the book Moby Dick (``melville-moby_dick.txt``) which you can find in the ``gutenberg`` corpus. Return the word counts sorted by frequency (most frequent word first) before and after cleaning the list of tokens with your function from __a)__.

_Hint: Take a look at_ ``defaultdict`` _and_ ``Counter`` _from the Python module_ ``collections``.

In [30]:
nltk.download('gutenberg')
from nltk.corpus import gutenberg
from collections import defaultdict

words = gutenberg.words('melville-moby_dick.txt')

# automatically creates new key if not present
word_count = defaultdict(int)  # initializes values of new key with 0 --> int() without arguments
for w in words:
    word_count[w]+=1

#print(word_count)

# sort by most frequent words (by value)
sorted(word_count.items(), key=lambda i: i[1], reverse=True)
# sorted(a.items(), key =lambda y: y[1], reverse = True)

[nltk_data] Downloading package gutenberg to /root/nltk_data...
[nltk_data]   Package gutenberg is already up-to-date!


[(',', 18713),
 ('the', 13721),
 ('.', 6862),
 ('of', 6536),
 ('and', 6024),
 ('a', 4569),
 ('to', 4542),
 (';', 4072),
 ('in', 3916),
 ('that', 2982),
 ("'", 2684),
 ('-', 2552),
 ('his', 2459),
 ('it', 2209),
 ('I', 2124),
 ('s', 1739),
 ('is', 1695),
 ('he', 1661),
 ('with', 1659),
 ('was', 1632),
 ('as', 1620),
 ('"', 1478),
 ('all', 1462),
 ('for', 1414),
 ('this', 1280),
 ('!', 1269),
 ('at', 1231),
 ('by', 1137),
 ('but', 1113),
 ('not', 1103),
 ('--', 1070),
 ('him', 1058),
 ('from', 1052),
 ('be', 1030),
 ('on', 1005),
 ('so', 918),
 ('whale', 906),
 ('one', 889),
 ('you', 841),
 ('had', 767),
 ('have', 760),
 ('there', 715),
 ('But', 705),
 ('or', 697),
 ('were', 680),
 ('now', 646),
 ('which', 640),
 ('?', 637),
 ('me', 627),
 ('like', 624),
 ('The', 612),
 ('their', 612),
 ('are', 586),
 ('they', 586),
 ('an', 582),
 ('some', 578),
 ('then', 571),
 ('my', 564),
 ('when', 553),
 ('upon', 538),
 ('out', 529),
 ('into', 520),
 ('man', 508),
 ('ship', 507),
 ('up', 505),
 ('mor

In [19]:
from collections import Counter

words_cleaned = clean(words)

# subclass of dict for countinga
word_count_dict = Counter(words_cleaned)  # counts occurences in given iterable object (StreamBackedCorpusView (looks like list))

#print(word_count_dict)

# sorted by frequency
word_count_dict.most_common()

[('--', 1070),
 ('whale', 906),
 ('one', 889),
 ('like', 624),
 ('upon', 538),
 ('man', 508),
 ('ship', 507),
 ('Ahab', 501),
 ('."', 489),
 ('ye', 460),
 ('old', 436),
 ('sea', 433),
 ('would', 421),
 ('head', 335),
 ('though', 335),
 ('boat', 330),
 ('time', 324),
 ('long', 318),
 ('said', 302),
 (',"', 302),
 ('yet', 300),
 ('still', 299),
 ('great', 293),
 ('two', 285),
 ('seemed', 283),
 ('must', 282),
 ('Whale', 282),
 ('last', 277),
 ('way', 269),
 ('Stubb', 255),
 ('see', 253),
 ('?"', 252),
 ('Queequeg', 252),
 ('little', 247),
 ('round', 242),
 ('whales', 237),
 ('say', 237),
 ('three', 237),
 ('men', 236),
 ('thou', 232),
 ('may', 230),
 ('us', 228),
 ('every', 222),
 ('much', 218),
 ('could', 215),
 ('Captain', 215),
 ('first', 210),
 ('side', 208),
 ('hand', 205),
 ('ever', 203),
 ('Starbuck', 196),
 ('never', 195),
 ('good', 192),
 ('white', 191),
 ('deck', 189),
 ('thing', 188),
 ('almost', 186),
 ('water', 185),
 ('might', 183),
 ('go', 182),
 ('even', 181),
 ('made', 1

In [28]:
Counter(clean(gutenberg.words('melville-moby_dick.txt'))).most_common()


[('--', 1070),
 ('whale', 906),
 ('one', 889),
 ('like', 624),
 ('upon', 538),
 ('man', 508),
 ('ship', 507),
 ('Ahab', 501),
 ('."', 489),
 ('ye', 460),
 ('old', 436),
 ('sea', 433),
 ('would', 421),
 ('head', 335),
 ('though', 335),
 ('boat', 330),
 ('time', 324),
 ('long', 318),
 ('said', 302),
 (',"', 302),
 ('yet', 300),
 ('still', 299),
 ('great', 293),
 ('two', 285),
 ('seemed', 283),
 ('must', 282),
 ('Whale', 282),
 ('last', 277),
 ('way', 269),
 ('Stubb', 255),
 ('see', 253),
 ('?"', 252),
 ('Queequeg', 252),
 ('little', 247),
 ('round', 242),
 ('whales', 237),
 ('say', 237),
 ('three', 237),
 ('men', 236),
 ('thou', 232),
 ('may', 230),
 ('us', 228),
 ('every', 222),
 ('much', 218),
 ('could', 215),
 ('Captain', 215),
 ('first', 210),
 ('side', 208),
 ('hand', 205),
 ('ever', 203),
 ('Starbuck', 196),
 ('never', 195),
 ('good', 192),
 ('white', 191),
 ('deck', 189),
 ('thing', 188),
 ('almost', 186),
 ('water', 185),
 ('might', 183),
 ('go', 182),
 ('even', 181),
 ('made', 1

### Task 2: Levenshtein distance algorithm

__a)__ In this task we want to calculate the minimum edit distance between two input strings.

Write a function that implements the minimum edit distance algorithm (dynamic programming) from the lecture. Your function should get two strings as input and should return the minimum edit distance and a 2-dimensional numpy array that represents the corresponding edit distance table ``D``. Assume that insertion and deletion have a cost of 1. The cost of substitution should be specified by the user (default: 2).

Note, that the entry ``D[i][j]`` in the returned numpy array should correspond to the cell D(i,j) of the edit distance table from the lecture (i.e. the numpy array is a vertically flipped version of the table from the lecture).

__Example:__ _The edit distance table_ ``D`` _for a source string of length 3 and a target string of length 5 should be initialized as follows:_

```
[[0  1  2  3  4  5]
 [1  0  0  0  0  0]
 [2  0  0  0  0  0]
 [3  0  0  0  0  0]]
```

In [43]:
def edit_distance(str1: str, str2: str, cost_of_substitute: int=2) -> (int, NDArray[NDArray[int]]):
    '''
    :param str1: source string
    :param str2: target string
    :cost_of_substitute: cost for substituting mismatching letters
    :returns:
        - minimum edit distance of str1 and str2
        - minimum edit distance table
    '''
    I = len(str1) + 1  # +1 for hashtag symbol (empty string)
    J = len(str2) + 1
    D = np.zeros((I,J), dtype=int)

    # initialize first row and column
    D[:,0] = np.arange(I)  # index 0 of all elements (first column)
    D[0,:] = np.arange(J)  # all entries of element at index 0 (first row)

    for i in range(1,I):  # loop through rows
        for j in range(1,J):  # loop through columns
            sub = D[i-1, j-1] # init cost same letters
            if str1[i-1] != str2[j-1]: # input strings do not include hashtag symbol (empty string) => index-1 otherwise will exceed the length
                  sub += cost_of_substitute # not same letters

            D[i,j] = min(D[i-1,j] + 1, D[i,j-1] + 1, sub)  # new value

    return D[-1][-1], D
    # return D[I-1][J-1], D

In [44]:
dist, D = edit_distance("sitting", "kitten")
print(dist)
print(D)

5
[[0 1 2 3 4 5 6]
 [1 2 3 4 5 6 7]
 [2 3 2 3 4 5 6]
 [3 4 3 2 3 4 5]
 [4 5 4 3 2 3 4]
 [5 6 5 4 3 4 5]
 [6 7 6 5 4 5 4]
 [7 8 7 6 5 6 5]]


In [39]:
distance2, D2 = edit_distance("INTENTION", "EXECUTION")
print(distance2)
print(D2)
print(D2[9,9])

8
[[ 0  1  2  3  4  5  6  7  8  9]
 [ 1  2  3  4  5  6  7  6  7  8]
 [ 2  3  4  5  6  7  8  7  8  7]
 [ 3  4  5  6  7  8  7  8  9  8]
 [ 4  3  4  5  6  7  8  9 10  9]
 [ 5  4  5  6  7  8  9 10 11 10]
 [ 6  5  6  7  8  9  8  9 10 11]
 [ 7  6  7  8  9 10  9  8  9 10]
 [ 8  7  8  9 10 11 10  9  8  9]
 [ 9  8  9 10 11 12 11 10  9  8]]
8


In [40]:
list2 = [1,2,3,4,5]
list2[-1]

5