# Exercise 03: Minimum Edit Distance

In [1]:
from typing import List, Union, Dict, Set, Tuple
import numpy as np
from numpy.typing import NDArray

### Task 1: Preprocessing
In this task, use functions from ``nltk`` wherever possible.

In [2]:
import nltk

__a)__ Write a function that removes the punctuation (consider ``string.punctuation``) and all stopwords from a given text.

In [9]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [4]:
from nltk.corpus.reader.util import StreamBackedCorpusView

In [18]:


def clean(tokens: Union[List[str], StreamBackedCorpusView]) -> List[str]:
    """
    Cleans a list of tokens by removing punctuation and stopwords.

    :param tokens: list of tokens that should be cleaned
    :return: list of cleaned tokens
    """
    # Get the stopwords in English
    stop_words = set(stopwords.words('english'))

    # If the input is a StreamBackedCorpusView, convert it to a list
    if isinstance(tokens, StreamBackedCorpusView):
        tokens = list(tokens)

    # Clean the tokens by removing stopwords and punctuation
    cleaned_tokens = [
        token for token in tokens
        if token.lower() not in stopwords
    ]

    return cleaned_tokens

# Example usage
text = "This is an example sentence, with punctuation and stopwords!"
tokens = text.split()  # Tokenize the example text
cleaned_tokens = clean(tokens)
print(cleaned_tokens)


TypeError: argument of type 'WordListCorpusReader' is not iterable

In [ ]:
from nltk.corpus.reader.util import StreamBackedCorpusView

def clean(tokens: Union[List[str], StreamBackedCorpusView]) -> List[str]:
    """
    :param tokens: list of tokens that should be cleaned
    :return: list of cleaned tokens
    """
    # your code here
    return

In [13]:
res = i for i in tokens

<WordListCorpusReader in '/root/nltk_data/corpora/stopwords'>


In [14]:
# test
t1 = "I am happy to have you my dear friend!~"

In [16]:
print(clean(t1.split()))

['happy', 'dear', 'friend!~']


__b)__ Get the list of tokens from the book Moby Dick (``melville-moby_dick.txt``) which you can find in the ``gutenberg`` corpus. Return the word counts sorted by frequency (most frequent word first) before and after cleaning the list of tokens with your function from __a)__.

_Hint: Take a look at_ ``defaultdict`` _and_ ``Counter`` _from the Python module_ ``collections``.

### Task 2: Minimum Edit Distance

__a)__ In this task we want to calculate the minimum edit distance between two input strings.

Write a function that implements the minimum edit distance algorithm (dynamic programming) from the lecture. Your function should get two strings as input and should return the minimum edit distance and a 2-dimensional numpy array that represents the corresponding edit distance table ``D``. Assume that insertion and deletion have a cost of 1. The cost of substitution should be specified by the user (default: 2, i.e., Levenshtein distance).

Note, that the entry ``D[i][j]`` in the returned numpy array should correspond to the cell D(i,j) of the edit distance table from the lecture (i.e. the numpy array is a vertically flipped version of the table from the lecture).

__Example:__ _The edit distance table_ ``D`` _for a source string of length 3 and a target string of length 5 should be initialized as follows:_

```
[[0  1  2  3  4  5]
 [1  0  0  0  0  0]
 [2  0  0  0  0  0]
 [3  0  0  0  0  0]]
```

In [ ]:
def edit_distance(str1: str, str2: str, cost_of_substitute: int=2) -> (int, NDArray[NDArray[int]]):
    '''
    :param str1: source string
    :param str2: target string
    :cost_of_substitute: cost for substituting mismatching letters
    :returns:
        - minimum edit distance of str1 and str2
        - minimum edit distance table
    '''
    # your code here
    return