# Home Assignment 1 (35 pts)

Submit your solution via Ilias until 23.59h on Sunday, October 6th. Any later submission is not possible.

> Add blockquote



Submit your solutions in teams of 4 students. Unless explicitly agreed otherwise in advance, submissions from teams with more or less members will NOT be graded (i.e., count as failed).

**Make sure that all team members are part of the submitting group on Ilias.**

Only submit a notebook, do not submit the dataset(s) you used. Also, do NOT compress/zip your submission!

You may use the code from the exercises and basic functionalities that are explained in the official documentation of Python packages without citing, __all other sources must be cited__. In case of plagiarism (copying solutions from other teams or from the internet) ALL team members may be expelled from the course without warning.

#### General guidelines:
* Make sure that your code is executable, any task for which the code does not directly run on our machine will be graded with 0 points.
* If you use packages that are not available on the default or conda-forge channel, list them below. Also add a link to installation instructions.
* Ensure that the notebook does not rely on the current notebook or system state!
  * Use `Kernel --> Restart & Run All` to see if you are using any definitions, variables etc. that
    are not in scope anymore.
  * Do not rename any of the datasets you use, and load it from the same directory that your ipynb-notebook is located in, i.e., your working directory.
* Make sure you clean up your code before submission, e.g., properly align your code, and delete every line of code that you do not need anymore, even if you may have experimented with it. Minimize usage of global variables. Avoid reusing variable names multiple times!
* Ensure your code/notebook terminates in reasonable time.
* Feel free to use comments in the code. While we do not require them to get full marks, they may help us in case your code has minor errors.
* For questions that require a textual answer, please do not write the answer as a comment in a code cell, but in a Markdown cell below the code. Always remember to provide sufficient justification for all answers.
* You may create as many additional cells as you want, just make sure that the solutions to the individual tasks can be found near the corresponding assignment.
* If you have any general question regarding the understanding of some task, do not hesitate to post in the forum in Ilias, so we can clear up such questions for all students in the course.

Additional packages (if any):
 - Example: `powerlaw`, https://github.com/jeffalstott/powerlaw

In [2]:
from typing import List, Union, Dict, Set, Tuple
import numpy as np
from numpy.typing import NDArray

### Task 1: Regular expressions (9 pts)
In this task you are asked to create regular expressions that meet the specified conditions. Please use the ``re`` package for the following subtasks.

In [3]:
# import the re package
import re

__a)__ Write a regular expression that returns all integer numbers from a text that are surrounded by whitespaces. __(1 pt)__

In [4]:
text1a = 'there are 100 234 495people here.'
re.findall(r'\d+', text1a)  # your code here

['100', '234', '495']

__b)__ Write a regular expression that returns all valid years that are surrounded by whitespaces in a text. A valid year is a 4 digit number in the range from 0000 to 2024. __(2 pts)__  
You do not need to account for overlaps, e.g., `' 2023 2024 ' => [2023]` is ok. Bonus points if you do so (`' 2023 2024 ' => [2023,2024]`). __(+2 pts)__

In [21]:
text1b = 'before 1993, he was born. But till 2023, he has not been discorved. In 2024, things changed.'
re.findall(r'[01][0-9]{3}|20[0-2][0-4]',text1b) # [01][0-9]{3}: from 0000-1999 20[0-2][0-4]:from 2000-2024 |:choose from either

['1993', '2023', '2024']

__c)__ Write a regular expression that returns all dates in the format YYYY-MM-DD or YYYY/MM/DD from a given text. Make sure that YYYY is a valid year (see task __b)__), MM is a valid month (01 to 12) and DD is a valid day (01 to 31).
There is no need to make sure that e.g. XXXX-02-31 does not exist.  __(2 pts)__

In [34]:
text1c = '2024-05-27 is her birthday. The appointment she made is 2024/12/25.'
date1c = re.finditer(r'(([01][0-9]{3}|20[0-2][0-4])[/-](0[0-9]|1[0-2])[/-]([0-2][0-9]|3[01]))',text1c)
# (0[1-9]|1[0-2]): split the month of two parts, start with 0 or 1. for month starts with 0, it's possible from 01-09, for month starts with 1, it's possible from 10-12
# ([0-2][0-9]|3[01]): for days in months, there can be 31 days. Split to two parts, start with 0-2 or 3. the form is the same as the month
# [/-]: match both / or -
# (): to split the different part(the code for year, month and days)
for i in date1c:
  print(i.group())

2024-05-27
2024/12/25


In [25]:
abc = ['2024-05-27', '2024/12/25']
abc[1][1]

'0'

In [35]:
text1c = '2024-05-27 is her birthday. The date she made the appointment is 2024/04/25. Of course not 2024/04/31.'
date1c = re.finditer(r'(([01][0-9]{3}|20[0-2][0-4])[/-](((0[13578]|1[02])[/-]([0-2][0-9]|3[01]))|((0[469]|11)[/-]([0-2][0-9]|30))|(02[/-]([0-1][0-9]|2[0-8]))))',text1c)
# ([01][0-9]{3}|20[0-2][0-4])[/-]: YYYY/ or YYYY-, where YYYY < 2025
# (((0[13578]|1[02])[/-]([0-2][0-9]|3[01]))|: for month 1/3/5/7/8/10/12, there are 31 days
#   (0[13578]|1[02]): split the month of two parts, start with 0 or 1
#   ([0-2][0-9]|3[01]): split the days of two parts, start with 0-2 or 3
# ((0[469]|11)[/-]([0-2][0-9]|30))|: for month 4/6/9/11, there are 30 days, and form is same as before
# (02[/-]([0-1][0-9]|2[0-8]): for month 2, there are 28 days
for i in date1c:
  print(i.group())


2024-05-27
2024/04/25


__d)__ Assume you are given a list ``l`` of strings like the one below. Using regular expressions, return a list that contains all elements from ``l`` that don't contain both, the letter ``a`` and ``e`` and store the result in a variable ``l_filtered``.  __(2 pts)__

__Example:__ _given the list_  

``l = ["apple", "cucumber", "tomato", "zucchini", "pumpkin", "pear", "raspberry", "blueberry"]``  

_you should return_  

``l_filtered = ['cucumber', 'tomato', 'zucchini', 'pumpkin', 'blueberry']``.

In [38]:
# example list
l = ["apple", "cucumber", "tomato", "zucchini", "pumpkin", "pear", "raspberry", "blueberry"]

In [89]:
l_filtered = re.finditer(r'\b(?!((\w*[a]\w*[e]\w*)|(\w*[e]\w*[a]\w*)))\w+\b', str(l))
for i in l_filtered:
  print(i.group())


cucumber
tomato
zucchini
pumpkin
blueberry


In [77]:
l_filtered = re.finditer(r'\b(?!((\w*[a]\w*[e]\w*)|(\w*[e]\w*[a]\w*)))\w+\b', str(l))
for i in l_filtered:
  print(i.group())


cucumber
tomato
zucchini
pumpkin
blueberry


In [55]:
print(str(l))

['apple', 'cucumber', 'tomato', 'zucchini', 'pumpkin', 'pear', 'raspberry', 'blueberry']


__e)__ For the given string ``s`` with 4 lines, change the _whole_ word ``pot`` (i.e. ``pottery`` should not be changed) to ``1234`` only if it is at the start of a line.  __(2 pts)__

In [4]:
s = '''\
pottery clot pot
pot dot plot hot
spot rot pot got
not shot forgot'''

In [11]:
re.sub(r'(^[pot]\b)|\n(pot)\b', '1234',s)

'pottery clot pot 1234 dot plot hot\nspot rot pot got\nnot shot forgot'

### Task 2: Finding the most similar word (18 pts)
The goal of this task is, given a corpus, to find the most similar word for a provided word. As an example we will consider the King James Bible that is is included in the ``gutenberg`` corpus and we are looking to find the word that is most similar to ``god``. We consider two words similar if they appear in the same word context.

__a) Cleaning the input (3 pts)__

Write a function that, given a list of tokens, returns a list of tokens that we consider valid for our task. Moreover, all input tokens should be converted to lower case.

An *invalid* token is a token that
- is a punctuation mark (consider `string.punctuation`).
- is entirely numeric digits (e.g. `"123"`)
- optionally, if `remove_stopwords=True` then stopwords in the English language are also not considered valid tokens (use nltk's stopwords).

Use the function signature specified in the cell below.

In [ ]:
import nltk
from nltk.corpus.reader.util import StreamBackedCorpusView

def get_valid_tokens(tokens: Union[List[str], StreamBackedCorpusView], remove_stopwords: bool=False) -> List[str]:
    """
    :param tokens: list of tokens that should be cleaned
    :param remove_stopwords: bool indicating if stopwords should be removed
                             False by default
    :return: list of valid tokens
    """
    # your code here
    return

__b) Counting the surroundings (6 pts)__

In our simple model of word similarity we consider words as similar if they are being used in the same context (i.e. they have similar words surrounding them).

Implement a function that, given a list of words, returns the count of all words in a designated word's surrounding. The context size indicates how many words to the left and right we consider, i.e. a context size of 1 indicates that we only consider the words immediately before and after a central word to be in its context.

Your function should return a dictionary which maps each word $w$ from the input list to a dictionary. The inner dictionary should map each word that appears in the context of the central word $w$ to a number that indicates how often it appears in the context of $w$.

Make sure your implementation has linear complexity in the vocabulary / corpus length. Use the function signature specified in the cell below.

__Hint:__ Instead of the inner dictionary you can alternatively use `Counter` or `defaultdict` which can be found in the Python module `collections`. Moreover, consider the function ``ngrams`` from ``nltk``.

__Example:__ _For the input_
`['hi', 'james', 'how', 'are', 'you', 'hello', 'catherine', 'how', 'are', 'you']` _and_ `context_size=1`
_we wish to obtain:_
```
{'hi': {'james': 1},
 'james': {'hi': 1, 'how': 1},
 'how': {'james': 1, 'are': 2, 'catherine': 1},
 'are': {'how': 2, 'you': 2},
 'you': {'are': 2, 'hello': 1},
 'hello': {'you': 1, 'catherine': 1},
 'catherine': {'hello': 1, 'how': 1}}
```
__Explanation:__ _The word_ `hi` _is only surrounded by_ `james`_. The word_ `james` _is surrounded by_ `hi` _and_ `how` _. The word_ `how` _is surrounded by_ `james`_, by_ `catherine` _and by_ `are` _twice, ..._

_For_ `contextsize=2` _we obtain:_
```
{'hi': {'james': 1, 'how': 1},
'james': {'hi': 1, 'how': 1, 'are': 1},
'how': {'are': 2, 'you': 2, 'hi': 1, 'james': 1, 'hello': 1, 'catherine': 1},
'are': {'how': 2, 'you': 2, 'james': 1, 'hello': 1, 'catherine': 1},
'you': {'how': 2, 'are': 2, 'hello': 1, 'catherine': 1},
'hello': {'are': 1, 'you': 1, 'catherine': 1, 'how': 1},
'catherine': {'you': 1, 'hello': 1, 'how': 1, 'are': 1}}
```

In [ ]:
def get_surrounding_counts(tokens: Union[List[str], StreamBackedCorpusView], context_size: int) -> Dict[str, Dict[str, int]]:
    """
    :param tokens: list of tokens
    :param context_size: integer that indicates the number of context words that are considered on both sides of the central word
    :return: dict of dicts that holds the count of context words for each input token
    """
    # your code here
    return

__c) Keeping the top $k$ words in context (2 pts)__

To reduce the size of our result from task __b)__, we will only consider the most frequent context words for each token. Therefore, write a function that keeps only the $k$ most frequent words in the context of a designated word. Ties are resolved in lexicographic order (e.g. _**A**braham_ would be preferred to _**B**ethlehem_). The function should return a dictionary that maps each word in the outer dictionary to a __set__ of their top $k$ most frequent context words.

In [ ]:
def to_sets(context_dict: Dict[str, Dict[str, int]], k: int) -> Dict[str, Set[str]]:
    """
    :param context_dict: dict of dicts that holds the count of context words for each word
    :param k: integer that specifies how many context words should be kept
    :return: dict that maps each word to a set of its k most frequent context words
    """
    # your code here
    return

__d) Finding the most similar words (4 pts)__

Given a dictionary as obtained in task __c)__ and a word $w$, we want to find the words that have the highest similarity to $w$ in terms of their context. We operationalize context similarity with the Jaccard index (https://en.wikipedia.org/wiki/Jaccard_index).
The Jaccard index of two sets $A$ and $B$ (in our case the sets of context words) is defined as:

$J(A, B) = \frac{|A \cap B|}{|A \cup B|}$

Write a function that returns the words that have the highest similarity to an input word $w$ (ignoring the input word itself). Since several words may have the same Jaccard similarity to the input word, your function should return the set of words that are most similar to $w$ and the respective value of the Jaccard similarity. Use the function signature specified in the cell below.

In [ ]:
def find_most_similar_words(input_word: str, contexts: Dict[str, Set[str]]) -> (Set[str], float):
    """
    :param input_word: string that represents the word we are interested in
    :param contexts: dict that maps each word to a set of its most frequent context words
    :returns:
        - set of the most similar words to the input word
        - float that indicates the highest Jaccard similarity to the input word
    """
    # your code here
    return

__e) Bringing it all together (3 pts)__

Finally, we want to apply our functions to the King James Bible (`'bible-kjv.txt'`) that is part of the ``gutenberg`` corpus. We intend to find the word(s) that is (are) most similar to ``god``. Follow the steps below:

i) Obtain a list of all tokens from the King James Bible and store it in a variable ``tokens``.  

ii) Clean the list of tokens with your function from __a)__ to get the list of valid tokens (without removing stopwords) and store it in a variable ``valid_tokens``.  

iii) Apply your function from __b)__ to count the context words for all valid tokens with a ``context_size`` of 2 and store the result in a variable ``context_counts``.  

iv) Using your function from __c)__, keep only the 20 most frequent words in a valid tokens context and store the result in a variable ``context_words``.  

v) Finally, find the most similar words to the word _god_ with your function from __d)__ and store the set of most similar words in the variable ``set_god`` and the highest Jaccard similarity in the variable ``sim_god``.  

In [ ]:
# your code here

### Task 3: Minimum cost string alignment (8 pts)

In this tak we want to compute an alignment between two strings, that has minimum edit distance.

Implement a function that takes two strings and their edit distance matrix and returns a minimum cost alignment. You can assume that the edit distance matrix is provided by the function that you implemented in exercise 3, task 2, with a substitution cost of 2.

A minimum cost alignment consists of two strings that, printed below each other comprise the alignment, where insertions and deletions are represented by a ``*``. Use the function signature in the cell below.

__Example:__ _Given the input strings_ ``"INTENTION"`` _and_ ``"EXECUTION"`` _and the corresponding edit distance matrix:_

```
[[ 0  1  2  3  4  5  6  7  8  9]
 [ 1  2  3  4  5  6  7  6  7  8]
 [ 2  3  4  5  6  7  8  7  8  7]
 [ 3  4  5  6  7  8  7  8  9  8]
 [ 4  3  4  5  6  7  8  9 10  9]
 [ 5  4  5  6  7  8  9 10 11 10]
 [ 6  5  6  7  8  9  8  9 10 11]
 [ 7  6  7  8  9 10  9  8  9 10]
 [ 8  7  8  9 10 11 10  9  8  9]
 [ 9  8  9 10 11 12 11 10  9  8]]
```

  
_your function should return the two strings_ ``INTE***NTION`` _and_ ``***EXECUTION`` _that represent the alignment, when printed below each other:_

```
 INTE***NTION
 ***EXECUTION
```

 __Remark:__ _The alignment in the example above is not the only solution. In this task all alignments with minimum edit distance are accepted._
