# Exercise 1: Introduction to Python

### Use Python as a calculator to compute 256²

In [1]:
print(256**2)
# or
print(256*256)

65536
65536


### Put the strings "Hello" and "World!" in two variables. Concatenate both Strings and print them

In [2]:
hello = "Hello"
world = "World!"
 
print(hello + world)
print(hello + " " + world)

# or store concatenated string first
helloworld = hello + world

print(helloworld)
print(hello,world)


HelloWorld!
Hello World!
HelloWorld!
Hello World!


### Create a list that contains the 4 strings "alpha", "beta", "gamma", and "delta". Add "epsilon" to the end of this list

In [3]:
list1 = ["alpha", "beta", "gamma", "delta"]

# add to list
list1 = list1 + ["epsilon"]

# or add and reassign
list1 += ["zeta"]

# or use append()
list1.append("eta")

print(list1)

['alpha', 'beta', 'gamma', 'delta', 'epsilon', 'zeta', 'eta']


### Create a sublist with the first three elements of this list


In [4]:
# access elements by slicing: list[start:stop:step]
# returns elements from index 'start' to index 'stop'-1 at a step size 'step'

sublist1 = list1[0:3:1] 
# or shorter
sublist2 = list1[:3]   

print(sublist1)
print(sublist2)

['alpha', 'beta', 'gamma']
['alpha', 'beta', 'gamma']


### Write a Python program to construct the following pattern using for loops

In [5]:
for i in range(1,6):
    print("* " * i)
for i in range(4,0,-1):
    print("* " * i)

* 
* * 
* * * 
* * * * 
* * * * * 
* * * * 
* * * 
* * 
* 


In [6]:
# create lists with the range function
list3 = list(range(1, 6))
list4 = list(range(4, 0, -1))

print(list3)
print(list4)

# concatenate lists
star_list = list3 + list4
print(star_list)

[1, 2, 3, 4, 5]
[4, 3, 2, 1]
[1, 2, 3, 4, 5, 4, 3, 2, 1]


In [8]:
# loop through each element of the list
for i in star_list:
    print("* " * i)    # repeat the string "*" i times

* 
* * 
* * * 
* * * * 
* * * * * 
* * * * 
* * * 
* * 
* 


### Write a function that takes 3 input parameters and returns the product of these values

In [9]:
def my_product1(x, y, z):
    return x*y*z

# * operator allows arbitrary number of arguments
def my_product2(*x):
    res = 1
    for i in x:
        res *= i
    return res

In [10]:
# let's test the functions
print(my_product1(3, 5, 2))
print(my_product2(3, 5, 2))

30
30


### Write a Python function that takes an int as a parameter and checks if the number is prime or not.

In [11]:
# prime: integer larger than 1 that can only be divided by 1 and itself
def is_prime(x):
    if x <= 1:
        return False
    for i in range(2, x):
        if x % i == 0:    # % = modulo operator (returns the remainder of a division)
            return False
    return True

In [12]:
# test function
print(is_prime (2))
print(is_prime (23))
print(is_prime (21))

True
True
False


### Use your function to create a list that contains all primes from 2 to 100

In [13]:
print([x for x in range(2,101) if is_prime(x)])

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]


In [14]:
# define a helper function
def primes_between(start, stop):
    res = []
    for x in range(start, stop+1):
        if is_prime(x):
            res.append(x)
    return res

print(primes_between(2, 100))

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]


### Write a function that simulates dice rolls (6-sided dices)
- Write a function that has the number of dice rolls as the input parameter
- The output should be a dictionary that stores how often each result of a roll (1-6) occurred (keys: numbers from 1 to 6, values: how often the number was rolled)
- You can use the randint() function from the random package

In [15]:
# load the random package
import random

def roll_dice(rolls):
    res = {1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0}    # set up the dictionary    
    for i in range(rolls):
        x = random.randint(1, 6)                  # roll the dice
        # print(x)
        res[x] = res[x] + 1                       # increment the counter in the dictionary 
    return res

print(roll_dice(5))

{1: 1, 2: 1, 3: 0, 4: 0, 5: 3, 6: 0}


In [16]:
def roll(rolls):
    d = {k:0 for k in range(1,7)}
    for i in range(rolls):
        d[random.randint(1,6)] +=1
    return d
roll(5)

{1: 1, 2: 2, 3: 0, 4: 1, 5: 1, 6: 0}

### Combine two dictionaries by adding values for common keys.
d1 = {'a': 100, 'b': 200, 'c':300}

d2 = {'a': 300, 'b': 200, 'd':400}

Sample output: {'a': 400, 'b': 400, 'd': 400, 'c': 300}

In [17]:
def merge_dicts(d1, d2):
    d = {}
    for key, value in d1.items():    
        d[key] = value                 # take all key:value pairs from first dict
    for key, value in d2.items():
        if key in d:
            d[key] = d[key] + value    # sum values if it's the same key
        else:
            d[key] = value             # add key:value pair if not already present
    return d

In [18]:
def merge(d1,d2):
    d = d1.copy()
    for k,v in d2.items():
        if k in d:
            d[k] += v
        else:
            d[k] = v
    return d

In [19]:
# test the function
d1 = {'a': 100, 'b': 200, 'c':300}
d2 = {'a': 300, 'b': 200, 'd':400}

print(merge_dicts(d1, d2))
print(merge(d1,d2))

{'a': 400, 'b': 400, 'c': 300, 'd': 400}
{'a': 400, 'b': 400, 'c': 300, 'd': 400}


In [20]:
d1

{'a': 100, 'b': 200, 'c': 300}

### Create a list of lists. Then, write a list comprehension that creates a list with the lengths of each (sub)list in the primary list

In [21]:
llist = [[1, 1, 1], ['a', 'a'], [3.3], [4, 4, "b", 4, 4]]

len_llist = [len(x) for x in llist]

print(len_llist)

[3, 2, 1, 5]


### Exceptions

Write your own function *my_division* that gets two variables a and b and returns a divided by b. Catch the ZeroDivisionError that occurs if b equals 0 and return 1 in this case.

How could the same behavior be achieved without catching an exception?

In [22]:
# catching the exception
def my_division1(a, b):
    try:
        return a / b
    except ZeroDivisionError:    # call specific error, try-except also works without specifying error
        return 1
    
# without catching exception
def my_division2(a, b):
    if b == 0:
        return 1
    else:
        return a / b

In [23]:
# test
print(my_division1(6, 2))
print(my_division1(6, 0))

print(my_division2(6, 2))
print(my_division2(6, 0))

3.0
1
3.0
1


### File handling

Write a function that gets a letter and the path to a (text-)file on your harddrive as input parameters and computes a list as its output. The list should contain one number for each line. The i-th line shows, how often the given letter occurs in line number i in the text file. Test your function on "ftest.txt", which was provided in this exercise!

In [24]:
!cat ftest.txt

a
ab
baba
abba
ba

In [25]:
def count_letter(letter, path):
    res = []
    # with -- as closes file automatically at end of statement
    with open(path, 'r') as f:                # 'r' = open file for reading only
        for line in f:
            res.append(line.count(letter))    # built-in count() function for strings
    return res

count_letter('a',"ftest.txt")

[1, 1, 2, 2, 1]

## Numpy

In this last set of tasks, you will have to work with numpy, the fundamental package for scientific computing with Python.
Make sure to execute the cell below to import the package, we will usually use the abbreviation np for numpy to obtain shorter code.

In [26]:
import numpy as np

### Create a numpy array with 20 rows and 10 columns, where all values are set to zero

In [27]:
a = np.zeros((20, 10))
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

### Create an array with the same shape containing all natural numbers 0-199

In [28]:
np.arange(200)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [29]:
a = np.arange(200).reshape((20, 10))
a

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169

### Create a 4-dimensional array with exactly 16 elements and set all values to a random integer smaller than 5
You can use the Random Generator from numpy (documentation: https://numpy.org/doc/stable/reference/random/generator.html)

In [30]:
from numpy.random import default_rng

# get a new instance of the random number generator
rng = default_rng()    

a = rng.integers(5, size=(2,2,2,2))
a

array([[[[4, 0],
         [4, 3]],

        [[4, 1],
         [4, 2]]],


       [[[4, 1],
         [2, 4]],

        [[1, 4],
         [2, 1]]]])

In [31]:
a.shape

(2, 2, 2, 2)

### What is the mean of all values contained in this array?

In [32]:
print(a.mean())
# or 
print(np.mean(a))

2.5625
2.5625


### Select a sub-array containing exactly two elements of that array!

In [33]:
# slicing for arrays similar as for lists
print(a[1][1][0])  
# or
print(a[1, 1, 0,:])    

[1 4]
[1 4]


### Given a numpy array, return a new numpy array that contains only the elements that are greater than 100

In [34]:
a>100

array([[[[False, False],
         [False, False]],

        [[False, False],
         [False, False]]],


       [[[False, False],
         [False, False]],

        [[False, False],
         [False, False]]]])

In [35]:
a = np.array([1, 2, -3, 101, 500, 2, 302])

a[a>100]

array([101, 500, 302])

Numpy provides efficient implementations of linear algebra functions, mainly because of static typing and linking against efficient [BLAS](https://en.wikipedia.org/wiki/Basic_Linear_Algebra_Subprograms) libraries.  

In [65]:
dim = 500
a = b = [[j for j in range(dim)] for i in range(dim)]
a_np = b_np = np.array(a)
a_np.dtype

dtype('int64')

In [66]:
%%time
x = np.matmul(a_np,b_np)

CPU times: user 83.6 ms, sys: 3.5 ms, total: 87.1 ms
Wall time: 84.8 ms


In [73]:
a_np = b_np = np.array(a).astype('float32') # BLAS typically optimized for float operations => even better performance than with int

In [74]:
%%time
x = np.matmul(a_np,b_np)

CPU times: user 55 ms, sys: 1.65 ms, total: 56.7 ms
Wall time: 14.5 ms


In [69]:
def matmul(m1,m2):
    rows_m1 = len(m1)
    cols_m2 = len(m2[0])
    c = [[j for j in range(rows_m1)] for i in range(cols_m2)]
    for row in range(rows_m1):
        for col in range(cols_m2):
            row_m1 = m1[row]
            col_m2 = [x[col] for x in m2]
            c[row][col] = sum([row_m1[i]*col_m2[i] for i in range(len(row_m1))])
    return c

In [70]:
%%time
x = matmul(a,b)

CPU times: user 5.73 s, sys: 17.7 ms, total: 5.75 s
Wall time: 5.75 s
