<a href="https://colab.research.google.com/github/andy7622y/myfb/blob/main/IS557/1exercise_07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# For these tasks try to make your code as concise as possible. Try to avoid using for loops

## Create an numpy array of length 100 with 0s on all even position and 3s on all odd positions

In [ ]:
import numpy as np

In [ ]:
a = np.zeros(100,dtype = int)
a[::2] = 3
a

array([3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0,
       3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0,
       3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0,
       3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0,
       3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0])

## Create a numpy array containing number from 100 to 200
Hint: there is a special function for that similar to range for lists

In [ ]:
np.arange(100,201)

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
       152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164,
       165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177,
       178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190,
       191, 192, 193, 194, 195, 196, 197, 198, 199, 200])

## Compute a Euclidean distance between two points represented by numpy arrays

In [ ]:
a = np.array((3,4))
b = np.array((2,2))
dist = np.linalg.norm(a-b)
dist

2.23606797749979

## Create a 4x6 array containing 1s on the borders and 0s inside

In [ ]:
I = 7
J = 6
b = np.zeros((I,J),dtype = int)
for i in range(I):
  if i == 0 or i == I-1:
    for j in range(J):
      b[i][j] = 1
  else:
      b[i][0] = 1
      b[i][-1] = 1

b

array([[1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1]])

## Swap the first and the third rows of this array

## Create a 8x8 array to represent a chess board, such as that 0s correspond to white squares and 1s to black squares

## Ploting trajectory
If an object is thrown into the air with a velocity $v$ and angle $\alpha$ from horizontal then its trajectory can be computed using the following formula:

$y = x\tan\alpha - \frac{gx^2}{2v^2\cos^2\alpha}$.

Plot the trajectory of an object for a specified $v$ and $\alpha$, experiment with different values of $\alpha$ by ploting multiple trajectories on the same plot.

Hint: np.linspace(start, end, N) function creates a numpy array with N numbers equally spaced between start and end