# Numpy

## Create a 10x10 matrix with rows containing values from 1 to 10
Hint: broadcasting might be useful here

In [1]:
import numpy as np

In [3]:
x = np.ones((10,10))  # create a 2D array in the correct shape first
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [7]:
y = np.arange(1,11)  # create a (smaller) 1D array with values 1…10
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
x * y  # use broadcasting and element-wise multiplication to fill the rows

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

## Create a 10x10 matrix with columns containing values from 1 to 10

In [10]:
z = y.reshape((10,1))  # create a 2D column vector in the correct shape
z

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [11]:
x * z  # again, use broadcasting and element-wise multiplication

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.]])

## Replacing elements
Create a 4x4 array containing random numbers from 0 to 1.
Now replace all the elements of this array with
1) 1 if the element was higher than average

2) -1 if the element was lower than average

3) 0 if the element was equal to the average

In [13]:
x = np.random.random((4,4))  # create the random numbers
x

array([[0.11842359, 0.13593805, 0.397416  , 0.73195851],
       [0.02318478, 0.35919059, 0.68752676, 0.17707807],
       [0.15560517, 0.31839879, 0.50276321, 0.82262517],
       [0.46453265, 0.19607316, 0.06107695, 0.69649629]])

In [14]:
mean_x = np.mean(x)  # calculate the mean
mean_x

0.3655179833223915

In [16]:
x > mean_x  # create a boolean index

array([[False, False,  True,  True],
       [False, False,  True, False],
       [False, False,  True,  True],
       [ True, False, False,  True]])

In [18]:
# modify the array accordingly
x[x > mean_x] = 1
x[x < mean_x] = -1
x[x == mean_x] = 0
x

array([[-1., -1.,  1.,  1.],
       [-1., -1.,  1., -1.],
       [-1., -1.,  1.,  1.],
       [ 1., -1., -1.,  1.]])

<hr>

# Pandas

## Open file adult.csv as Pandas' DataFrame. Specify that missing values are denoted by '?'

The file is available in the ILIAS folder.

You can learn a bit more about this dataset [here](https://archive.ics.uci.edu/ml/datasets/adult)

In [19]:
import pandas as pd

In [24]:
df = pd.read_csv('adult.csv', na_values='?')  # load from csv
df.head()

age         workclass  fnlwgt  education  education-num  \
0   NaN         State-gov   77516  Bachelors             13   
1  50.0  Self-emp-not-inc   83311  Bachelors             13   
2  38.0           Private  215646    HS-grad              9   
3  53.0           Private  234721       11th              7   
4  28.0           Private  338409  Bachelors             13   

       marital-status         occupation   relationship   race     sex  \
0       Never-married       Adm-clerical  Not-in-family  White    Male   
1  Married-civ-spouse    Exec-managerial        Husband  White    Male   
2            Divorced  Handlers-cleaners  Not-in-family  White    Male   
3  Married-civ-spouse  Handlers-cleaners        Husband  Black    Male   
4  Married-civ-spouse     Prof-specialty           Wife  Black  Female   

   capital-gain  capital-loss  hours-per-week native-country  class  
0          2174             0              40  United-States  <=50K  
1             0             0              13  United-States  <=50K  
2             0             0              40  United-States  <=50K  
3             0             0              40  United-States  <=50K  
4             0             0              40           Cuba  <=50K

## What is the mean 'working time per week'?

In [25]:
df.describe()

age        fnlwgt  education-num  capital-gain  capital-loss  \
count  48841.000000  4.884200e+04   48842.000000  48842.000000  48842.000000   
mean      38.643578  1.896641e+05      10.078089   1079.067626     87.502314   
std       13.710650  1.056040e+05       2.570973   7452.019058    403.004552   
min       17.000000  1.228500e+04       1.000000      0.000000      0.000000   
25%       28.000000  1.175505e+05       9.000000      0.000000      0.000000   
50%       37.000000  1.781445e+05      10.000000      0.000000      0.000000   
75%       48.000000  2.376420e+05      12.000000      0.000000      0.000000   
max       90.000000  1.490400e+06      16.000000  99999.000000   4356.000000   

       hours-per-week  
count    48842.000000  
mean        40.422382  
std         12.391444  
min          1.000000  
25%         40.000000  
50%         40.000000  
75%         45.000000  
max         99.000000

## What is the mean age of women and men in this dataset?


In [31]:
# Select only the Women
df[df['sex'] == 'Female'].head()

age workclass  fnlwgt  education  education-num         marital-status  \
4   28.0   Private  338409  Bachelors             13     Married-civ-spouse   
5   37.0   Private  284582    Masters             14     Married-civ-spouse   
6   49.0   Private  160187        9th              5  Married-spouse-absent   
8   31.0   Private   45781    Masters             14          Never-married   
12  23.0   Private  122272  Bachelors             13          Never-married   

         occupation   relationship   race     sex  capital-gain  capital-loss  \
4    Prof-specialty           Wife  Black  Female             0             0   
5   Exec-managerial           Wife  White  Female             0             0   
6     Other-service  Not-in-family  Black  Female             0             0   
8    Prof-specialty  Not-in-family  White  Female         14084             0   
12     Adm-clerical      Own-child  White  Female             0             0   

    hours-per-week native-country  class  
4               40           Cuba  <=50K  
5               40  United-States  <=50K  
6               16        Jamaica  <=50K  
8               50  United-States   >50K  
12              30  United-States  <=50K

In [33]:
# Select the column 'age' for all women
df[df['sex'] == 'Female']['age']

4        28.0
5        37.0
6        49.0
8        31.0
12       23.0
         ... 
48826    50.0
48827    55.0
48828    38.0
48834    25.0
48837    39.0
Name: age, Length: 16192, dtype: float64

In [34]:
# Get the mean age of all women
df[df['sex'] == 'Female']['age'].mean()

36.92798913043478

In [35]:
# Get the mean age of all men
df[df['sex'] == 'Male']['age'].mean()

39.49441024227388