# Summary

This lecture is meant to showcase fundamental behavior of Python and the data handeling packages we discussed in this course. While it does not include a recap on file handeling, visualization, or machine learning, those lectures are still also relevant for the exam.

## Operators & Data Types

In [31]:
# Basic Numerical Operators
3 + 2, 3 - 2, 3 * 2, 3**2, 3/2, 3//2, 3 % 2

(5, 1, 6, 9, 1.5, 1, 1)

In [32]:
# Variables
x = 5
a = b = 2
a = a ** 3
x += 1
a, b, x

(8, 2, 6)

In [33]:
# Relational Operators
a = 3
a < 4, a > 3, a <= 4, a >= 3, a != 3.0, a == 3.0

(True, False, True, True, False, True)

In [34]:
# Data Types
a = 3
b = 3.0
c = 3e4
d = '3'
e = True
type(a), type(b), type(c), type(d), type(e), type(int(d)), type(b//2), type(a + b), type(str(a) + d), type(a + e), type(a > c)
# type(a + d) would fail, a needs to be explicitely cast to type str first

(int, float, float, str, bool, int, float, float, str, int, bool)

In [35]:
# Strings
a = "Hello"
len(a), a.lower(), a.upper(), a.replace('e', 'a'), a.startswith('e'), a.split('l'), a * 2, a > 'World', [c*2 for c in a]

(5,
 'hello',
 'HELLO',
 'Hallo',
 False,
 ['He', '', 'o'],
 'HelloHello',
 False,
 ['HH', 'ee', 'll', 'll', 'oo'])

## Data Structures

In [36]:
# Lists
l = [5,2]
m = l.copy()
m.append('t')
m[0] = 0
m.reverse()
l.sort()
r = range(4)
m, len(m), max(l), l*2, l+m, type(r), type(list(r)), list(r), l[1], l[:2:2], l[-1]

(['t', 2, 0],
 3,
 5,
 [2, 5, 2, 5],
 [2, 5, 't', 2, 0],
 range,
 list,
 [0, 1, 2, 3],
 5,
 [2],
 5)

In [37]:
# List Comprehensions
r = range(4)
[x**2 for x in r], [x for x in r if x>2], ['<' if x<3 else '>=' for x in r]

([0, 1, 4, 9], [3], ['<', '<', '<', '>='])

In [38]:
# Lists of Lists
l = [[1,2],[3,4]]
len(l), l[0], l[1][1], l[:][:-1]

(2, [1, 2], 4, [[1, 2]])

In [39]:
# Tuples
t = (5, 2)
t1 = (1,) # a tuple with only one element
x, y = t
#t[0] = 1 would fail because tuples do not support item assignment
len(t), x, y, type(t1), t*2

(2, 5, 2, tuple, (5, 2, 5, 2))

In [40]:
# Sets
s = {5, 2, 2}
# s[0] = 1 would fail because tuples do not support item assignment
s.add(3)
len(s), s, {i*2 for i in s}

(3, {2, 3, 5}, {4, 6, 10})

In [41]:
# Dictionaries
d = {'a': 1, 'b': 2}
d['a'] = a
d['b'] = {'b1': 2, 'b2': 3}
len(d), d['a'], list(d.items()), list(d.keys()), list(d.values()), {k: k*2 for k in range(2)}

(2,
 'Hello',
 [('a', 'Hello'), ('b', {'b1': 2, 'b2': 3})],
 ['a', 'b'],
 ['Hello', {'b1': 2, 'b2': 3}],
 {0: 0, 1: 2})

## Flow Control

In [42]:
# Conditions
x = y = 2
if x>0 and x < 3:
    print('yes')
elif not y>0: print('also yes')
else: print('no')
#    print('not at all') would fail because one can only either use the same line or an indented block

yes


In [43]:
# For-Loops
for a in ['a', 'b', 'c']:
    print(a)
for i, a in enumerate([1,2,3]):
    print(i, '-', a)
for i in range(3):
    print(i)

a
b
c
0 - 1
1 - 2
2 - 3
0
1
2


In [44]:
# While-Loops
i = 0
while i<10:
    if i>5: break
    print(i)
    i += 1

0
1
2
3
4
5


## Functions

In [45]:
# Definition and Arguments
def func(a, b, *args, param=2, **kwargs):
    print(args, kwargs) # optional arguments & more keyword arguments
    return a*b*param
t = (4, 5)
func(2, 3), type(func), func(*t), func(1,1,4), func(1,3,param=2), func(1,3,4,param=2), func(1,3,x=2)
# func(1,param=2,1) wouldn't work because positional arguments must come first
# func(1) wouldn't work because positional arguments are required

() {}
() {}
(4,) {}
() {}
(4,) {}
() {'x': 2}


(12, function, 40, 2, 6, 6, 6)

In [46]:
# Variable Scope
x = 2
y = 5
def func():
    y = 3
    print(x, y) # global variables are available within functions and can be overwritten
func()
y # local variables (overwrites) don't change the global variable

2 3


5

In [47]:
# Lambda Functions
f = lambda x:x*2
f(2), type(f), sorted([(6,2),(5,4),(4,6)], key=lambda x:x[1], reverse=True)

(4, function, [(4, 6), (5, 4), (6, 2)])

In [48]:
# Recursive Functions
def func(s):
    if len(s) == 1 or (len(s) == 2 and s[0]==s[1]):
        return True
    if s[0] != s[-1]:
        return False
    return func(s[1:-1])
func('reliefpfeiler')

True

## Objects and Classes

In [49]:
# Defining a Class
class A:
    def __init__(self):  # gets called when a new instance is created
        self.a = 3
        self.b = 4
    def __str__(x): # the 'self' variable can have a different name, but this should be avoided
        return 'The value is: ' + str(x.a)
    def __repr__(self):
        return self.__str__()
    def __eq__(self, other):
        if not isinstance(other, A): return False  # ensure that the other is an object of the same class
        return self.a == other.a
    def func(self, x, y):  # a custom function inside the class
        return self.b * y + x

my_a = A()
my_a.a = 5
my_a2 = A()
my_a, my_a.b, my_a == my_a2

(The value is: 5, 4, False)

In [50]:
# Modules inside the Python Standard Library
import math
import random
import datetime

l = [2,3,4]
random.shuffle(l)
math.log(math.e**3), random.random(), random.randint(0,9), l, datetime.datetime.today().weekday(), datetime.datetime.now().minute

(3.0, 0.5225584854162375, 2, [2, 4, 3], 1, 2)

## Numpy

In [51]:
import numpy as np

In [52]:
# Element-Wise Operations
np.array([2,3]*2), np.array([2,3])*2

(array([2, 3, 2, 3]), array([4, 6]))

In [53]:
# Initializing Arrays
np.empty((2, 3)), np.zeros(2), np.ones(3), np.arange(1,8,2)

(array([[0., 0., 0.],
        [0., 0., 0.]]),
 array([0., 0.]),
 array([1., 1., 1.]),
 array([1, 3, 5, 7]))

In [54]:
# Shapes and Broadcasting
x = np.array([[1,2], [3,4], [5,6]])
x.ndim, x.shape, x.T.shape, x.T, x.reshape(6,1), x.flatten(), x*2, x*[1,2], x.T*[1,2,3]

(2,
 (3, 2),
 (2, 3),
 array([[1, 3, 5],
        [2, 4, 6]]),
 array([[1],
        [2],
        [3],
        [4],
        [5],
        [6]]),
 array([1, 2, 3, 4, 5, 6]),
 array([[ 2,  4],
        [ 6,  8],
        [10, 12]]),
 array([[ 1,  4],
        [ 3,  8],
        [ 5, 12]]),
 array([[ 1,  6, 15],
        [ 2,  8, 18]]))

In [55]:
# Selectings from Arrays
x = np.array([[1,2], [3,4], [5,6]])
x % 2 == 0, x[x % 2 == 0], x[:2], x[:,::2]

(array([[False,  True],
        [False,  True],
        [False,  True]]),
 array([2, 4, 6]),
 array([[1, 2],
        [3, 4]]),
 array([[1],
        [3],
        [5]]))

## Pandas

In [56]:
import pandas as pd

In [84]:
# Initializing DataFrames
pd.DataFrame([[4,7,3], [5,6,2]]), pd.DataFrame([(4,7,3), (5,6,2)], columns=['A', 'B', 'C']), \
    pd.DataFrame([{'A': 4, 'B': 7, 'C': 3}, {'A': 5, 'B': 6, 'C': 2}])

(   0  1  2
 0  4  7  3
 1  5  6  2,
    A  B  C
 0  4  7  3
 1  5  6  2,
    A  B  C
 0  4  7  3
 1  5  6  2)

In [79]:
# Storing and Loading Data
df = pd.DataFrame([(4,7,3), (5,6,np.NaN)], columns=['A', 'B', 'C'])
df.to_csv('example.csv', index=False)
df2 = pd.read_csv('example.csv', index_col=None)
df2

A  B    C
0  4  7  3.0
1  5  6  NaN

In [106]:
# Filters
df_sorted = df.sort_values('B')
df_cleaned = df.dropna()
df_tail = df.tail(1)
list(df['A']), type(df.A), list(df[['A', 'C']].loc[0]), len(df_cleaned.A), list(df_tail.B)

([4, 5], pandas.core.series.Series, [4.0, 3.0], 1, [6])

In [110]:
# Boolean Filters
list((df.A > 3) & (df.B < 7)), list(df[(df.B > 6) | (df.C.notna())].A), list(df[df.A % 2 == 0].C)

([False, True], [4], [3.0])

In [93]:
# (Row) Indices
list(df_sorted.loc[0]), list(df_sorted.iloc[0]), list(df_sorted.reset_index(drop=False).loc[0])

([4.0, 7.0, 3.0], [5.0, 6.0, nan], [1.0, 5.0, 6.0, nan], [4.0, 7.0, 3.0])

In [100]:
# Statistics
df.A.sum(), df.B.count(), df.B.mean(), df.C.std()

(9, 2, 6.5, nan)

## Web Scraping

In [111]:
from bs4 import BeautifulSoup

webpage = '''
<html>
    <head>
        <title>Hello World</title>
    </head>
    <body>
        <header>
            <ul id='nav'>
                <li class='nav_main'>Home</li>
                <li class='nav_other'>About</li>
            </ul>
        </header>
        <article class='report'>
            <h1 class='much_bold'>Important Headline</h1>
            <section>
                <h2 id='heading2'>Less important headline</h2>
                <p>paragraph</p>
                <p>another paragraph</p>
            </section>
        </article>
    </body>
</html>
'''
soup = BeautifulSoup(webpage, 'html.parser')

In [125]:
# selecting elements
str(soup.p), soup.li.text, soup.find(name='h2')['id'], [el.text for el in soup.find_all('li')]

('<p>paragraph</p>', 'Home', 'heading2', ['Home', 'About'])

In [135]:
# CSS selectors
soup.select('title')[0].text, len(soup.select('li.nav_main')), len(soup.select('li .nav_main')), soup.select('#nav')[0].text.replace('\n', '')

('Hello World', 1, 0, 'HomeAbout')

In [150]:
# navigation
soup.select('ul')[0].parent.name, list(soup.ul.children)[1].text, list(soup.p.next_siblings)[1].text

('header', 'Home', 'another paragraph')